# Generated by Django 5.2.12 on 2026-05-23 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="eco_rating",
            field=models.IntegerField(default=80),
        ),
    ]
