# Generated by Django 5.2.12 on 2026-05-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_product_eco_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.CharField(default="fas fa-shopping-bag", max_length=50),
        ),
    ]
